# Generated by Django 5.0.1 on 2024-01-20 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_remove_room_name_alter_room_room_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="room_id",
            new_name="code",
        ),
    ]
