# Generated by Django 5.0.1 on 2024-01-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='answered_count',
            field=models.IntegerField(default=0),
        ),
    ]
