# Generated by Django 5.0.1 on 2024-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='end',
        ),
        migrations.AddField(
            model_name='room',
            name='outcome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
