# Generated by Django 5.0.1 on 2025-01-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_remove_room_end_room_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
