# Generated by Django 5.0.1 on 2025-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#836AAD', max_length=7),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_count',
            field=models.IntegerField(default=1),
        ),
    ]
