# Generated by Django 5.0.1 on 2025-01-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_alter_category_color_alter_room_max_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='key',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('icon', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='room.question')),
            ],
        ),
    ]
