# Generated by Django 5.0.1 on 2025-01-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_remove_question_key_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
