export const questionsByCategory = [
  {
    name: "food",
    theme: "#FF9090",
    questions: [
      {
        title: "Preferred Cuisine",
        key: "cuisine",
        theme: "#FF9090",
        options: [
          { index: 0, icon: "🇺🇸", value: "American" },
          { index: 1, icon: "🇨🇳", value: "Chinese" },
          { index: 2, icon: "🇻🇳", value: "Vietnamese" },
          { index: 3, icon: "🇲🇽", value: "Mexican" },
          { index: 4, icon: "🇰🇷", value: "Korean" },
          { index: 5, icon: "🇯🇵", value: "Japanese" },
          { index: 6, icon: "🇮🇳", value: "Indian" },
          { index: 7, icon: "🇹🇭", value: "Thai" },
          { index: 8, icon: "🇬🇷", value: "Greek" },
          { index: 9, icon: "🇮🇹", value: "Italian" },
          { index: 10, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "What Are You Craving?",
        key: "type",
        options: [
          { index: 0, icon: "🍚", value: "Rice" },
          { index: 1, icon: "🍖", value: "Meat" },
          { index: 2, icon: "🥗", value: "Salad" },
          { index: 3, icon: "🍞", value: "Bread" },
          { index: 4, icon: "🍜", value: "Noodle" },
          { index: 5, icon: "🍔", value: "Fast food" },
          { index: 6, icon: "🦐", value: "Seafood" },
          { index: 7, icon: "🍨", value: "Dessert" },
          { index: 8, icon: "🚫", value: "No Preference" },
        ],
      },
      {
        title: "Select Price Range",
        key: "price",
        options: [
          { index: 0, icon: "🪙", value: "$0-10" },
          { index: 1, icon: "💵", value: "$10-25" },
          { index: 2, icon: "💶", value: "$25-50" },
          { index: 3, icon: "💷", value: "$50-100" },
          { index: 4, icon: "💳", value: "$100+" },
          { index: 5, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Select Spicy Level",
        key: "spiciness",
        options: [
          { index: 0, icon: "😌", value: "Not spicy" },
          { index: 1, icon: "😅", value: "Mild spicy" },
          { index: 2, icon: "😤", value: "Moderately spicy" },
          { index: 3, icon: "🥵", value: "Very spicy" },
          { index: 4, icon: "🤯", value: "Extremely spicy" },
          { index: 5, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Warm or Cold",
        key: "temperature",
        options: [
          { index: 0, icon: "🍲", value: "Warm" },
          { index: 1, icon: "🍨", value: "Cold" },
          { index: 2, icon: "🚫", value: "No Preference" },
        ],
      },
    ],
  },
  {
    name: "activity",
    theme: "#7E518E",
    questions: [
      {
        title: "When?",
        key: "time",
        options: [
          { index: 0, icon: "🌅", value: "Morning" },
          { index: 1, icon: "🏞️", value: "Afternoon" },
          { index: 2, icon: "🏙️", value: "Evening" },
          { index: 3, icon: "🌃", value: "Late-night" },
          { index: 4, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Group Size?",
        key: "size",
        options: [
          { index: 0, icon: "🧑", value: "Solo" },
          { index: 1, icon: "👫", value: "Date (2)" },
          { index: 2, icon: "👨‍👩‍👦", value: "Small (3-6)" },
          { index: 3, icon: "👫👬", value: "Medium (7-10)" },
          { index: 4, icon: "👨‍👩‍👧‍👦👨‍👩‍👧‍👦", value: "Large (10+)" },
          { index: 5, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Indoor or Outdoor?",
        key: "place",
        options: [
          { index: 0, icon: "🏠", value: "Indoor" },
          { index: 1, icon: "🪂", value: "Outdoor" },
          { index: 2, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Vibe?",
        key: "mood",
        options: [
          { index: 0, icon: "⚡", value: "Energetic" },
          { index: 1, icon: "❤️", value: "Romantic" },
          { index: 2, icon: "🛋️", value: "Cozy" },
          { index: 3, icon: "❄️", value: "Chill" },
          { index: 4, icon: "🎨", value: "Creative" },
          { index: 5, icon: "💎", value: "Luxurious" },
          { index: 6, icon: "🌿", value: "Nature-filled" },
          { index: 7, icon: "🎉", value: "Playful" },
          { index: 8, icon: "🕊️", value: "Spiritual" },
          { index: 9, icon: "🤍", value: "Intimate" },
          { index: 10, icon: "⚽️", value: "Sports" },
          { index: 11, icon: "🚫", value: "No preference" },
        ],
      },
    ],
  },
  {
    name: "travel",
    theme: "#56B398",
    questions: [
      {
        title: "Destination?",
        key: "destination",
        options: [
          { index: 0, icon: "🏖️", value: "Beach" },
          { index: 1, icon: "🏔️", value: "Mountain" },
          { index: 2, icon: "🏙️", value: "City" },
          { index: 3, icon: "🌳", value: "Countryside" },
          { index: 4, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Travel Style?",
        key: "style",
        options: [
          { index: 0, icon: "🧗‍♂️", value: "Adventure" },
          { index: 1, icon: "🧘‍♀️", value: "Relaxation" },
          { index: 2, icon: "🏛️", value: "Cultural" },
          { index: 3, icon: "💎", value: "Luxury" },
          { index: 4, icon: "🎒", value: "Backpacking" },
          { index: 5, icon: "👨‍👩‍👧‍👦", value: "Family-friendly" },
          { index: 6, icon: "🧳", value: "Solo travel" },
          { index: 7, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Budget?",
        key: "budget",
        options: [
          { index: 0, icon: "🏷️", value: "Low" },
          { index: 1, icon: "💰", value: "Medium" },
          { index: 2, icon: "💎", value: "High" },
          { index: 3, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Duration?",
        key: "duration",
        options: [
          { index: 0, icon: "🏖️", value: "Day trip" },
          { index: 1, icon: "🗓️", value: "Weekend" },
          { index: 2, icon: "⏳", value: "1-2 weeks" },
          { index: 3, icon: "🌍", value: "1 month" },
          { index: 4, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Continent?",
        key: "continent",
        options: [
          { index: 0, icon: "🇪🇺", value: "Europe" },
          { index: 1, icon: "🌏", value: "Southeast Asia" },
          { index: 2, icon: "🏯", value: "East Asia" },
          { index: 3, icon: "🇺🇸", value: "North America" },
          { index: 4, icon: "🌎", value: "South America" },
          { index: 5, icon: "🌍", value: "Africa" },
          { index: 6, icon: "🇦🇺", value: "Australia" },
          { index: 7, icon: "🚫", value: "No preference" },
        ],
      },
      {
        title: "Travel Companion?",
        key: "companion",
        options: [
          { index: 0, icon: "🧑", value: "Solo" },
          { index: 1, icon: "👫", value: "Couple" },
          { index: 2, icon: "👨‍👩‍👧‍👦", value: "Family" },
          { index: 3, icon: "👫", value: "couple" },
          { index: 2, icon: "👨‍👩‍👧‍👦", value: "family" },
          { index: 3, icon: "👫👬", value: "friends" },
          { index: 4, icon: "🚫", value: "no preference" },
        ],
      },
    ],
  },
];
