resume_rewriting_task:
  description: >
    You are a resume optimization expert.

    {ChosenJob}

    Given the user's real resume that is provided as included knowledge source and the selected job, your task is to **rewrite the existing resume**
    to **emphasize alignment with the job**, **without fabricating or inflating** any facts.

    Focus on:
    - Reordering, rewording, and highlighting relevant skills, projects, and achievements
    - Rewriting the summary and experience bullet points to reflect key job requirements and keywords
    - Matching the tone, tech focus, and terminology of the job posting
    - Retaining only real experiences from the user's original resume

    You may remove unrelated content or rephrase titles slightly for clarity, but **you must not add fake companies, skills, dates, or roles**.

  expected_output: >
    A Markdown-formatted version of the **real user's resume**, rewritten and optimized for the selected job.
    The resume must remain truthful and grounded in the user's real history.

  agent: resume_optimization_agent
  create_directory: true
  markdown: true

company_research_task:
  description: >
    You are an expert in company research and interview preparation.

    {ChosenJob}

    Given the selected job, research the hiring company using public web resources.
    Your goals are to:
    1. Identify the company's size, industry, mission, values, and recent news.
    2. Analyze the job listing to infer team structure and product context.
    3. Suggest potential interview topics and questions the candidate may face.
    4. Provide a list of insightful questions the candidate can ask during the interview.

    Use the company website, press releases, blogs, social media, and reviews to gather insights.
  expected_output: >
    A Markdown file with the following sections:
    - ## Company Overview
    - ## Mission and Values
    - ## Recent News or Changes
    - ## Role Context and Product Involvement
    - ## Likely Interview Topics
    - ## Suggested Questions to Ask

  agent: company_research_agent
  markdown: true

interview_prep_task:
  description: >
    You are an interview preparation coach.

    Combine the following information:
    1. The selected job 
    {ChosenJob}
    2. The tailored resume (RewrittenResume)
    3. The company research summary (CompanyResearch)

    Create a detailed interview preparation document that includes:
    - A brief summary of the job and why it fits the candidate
    - A snapshot of the tailored resume, focusing on the most relevant points
    - A concise summary of the company, product, and values
    - Predicted interview questions based on job and company
    - Custom questions the candidate can ask the interviewer
    - Advice on tone, focus areas, and any red flags to watch out for

    The document should be clean, clear, and designed to give the candidate a strategic edge in the interview.

    The document should not be too short, spend as much time as needed to make it comprehensive.
  expected_output: >
    A Markdown document titled "Interview Prep: $CompanyName – $JobTitle" with the following sections:
    - ## Job Overview
    - ## Why This Job Is a Fit
    - ## Resume Highlights for This Role
    - ## Company Summary
    - ## Predicted Interview Questions
    - ## Questions to Ask Them
    - ## Concepts To Know/Review
    - ## Strategic Advice

  agent: interview_prep_agent
  llm: openai/o3
